### ISSUE TITLE
DCGAN

### ISSUE THREAD

**Issue by Atharv24** [vlgiitr/GenZoo#1]
Atharv, TensorFlow 1.13.1, MNIST, based on the TensorFlow tutorial for DCGANs

**Comment by dakshitagrawal97** [comment]
Hey Atharv,

Looks like you're the first one to open an issue!  Since no one has claimed this, you may work on it.  Once MNIST is done, kindly train DCGAN on other datasets mentioned in the README of the repository.

**Comment by dakshitagrawal97** [comment]
Since this model has now been added to GenZoo, I'm closing this issue.
